[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  # Formspree endpoint for “Request an Edit” form
  FORMSPREE_EDIT_ID = "mjkeqnvy"
  # Formspree endpoint for “Submit a Brand” form
  FORMSPREE_SUBMIT_ID = "mandryap"