/**
 *  Brand object as generated by tools/merge-brands.mjs.
 *  All keys are optional except `brand` and `slug`, and no extra keys
 *  should appear in the JSON produced for static deployment.
 */
export type Brand = {
  /* Primary identifiers */
  brand: string;
  slug: string;

  /* Simple strings */
  parent_company?: string;
  ownership_transparency?: string;
  hq?: string;
  /* Dates (normalized YYYY-MM-DD) */
  last_updated?: string;     // preferred canonical field
  latest_update?: string;    // legacy fallback
  updated_at?: string;       // legacy fallback
  assembled_in?: string;
  ingredient_sourcing?: string;
  ingredient_philosophy?: string;
  unique_offering?: string;
  glass_or_plastic?: string;
  sustainability?: string;
  non_profit_partner?: string;
  recalls_notices?: string;
  verification_status?: string;
  last_verified?: string; // normalised YYYY-MM-DD
  /** Free-text QA/testing notes pulled from Notion CSV column testing_qa_notes. */
  testing_qa_notes?: string;
  /** Licensed/clinically-tested ingredients (comma-delimited names) */
  clinically_tested?: string;

  /* Numbers */
  year_founded?: number;

  /* Booleans */
  self_manufactured?: boolean;
  in_house_testing?: boolean;
  made_in_usa?: boolean;
  proprietary_blends?: boolean;
  woman_owned?: boolean;
  vegan?: boolean;
  allergen_free?: boolean;

  /* Arrays */
  manufacturing_locations?: string[];
  certification?: string[];
  product_categories?: string[];
  product_types?: string[];
  top_products?: string[];
  /** 
   * List of citation URLs or objects with explicit titles.
   * Accepts plain string URLs for brevity or objects of shape:
   *   { url: string; title?: string }
   */
  sources?: (string | { url: string; title?: string })[];
};
