/**
 *  Brand object as generated by tools/merge-brands.mjs.
 *  All keys are optional except `brand` and `slug`, and no extra keys
 *  should appear in the JSON produced for static deployment.
 */
export type Brand = {
  /* Primary identifiers */
  brand: string;
  slug: string;

  /* Simple strings */
  parent_company?: string;
  ownership_transparency?: string;
  hq?: string;
  assembled_in?: string;
  ingredient_sourcing?: string;
  ingredient_philosophy?: string;
  unique_offering?: string;
  glass_or_plastic?: string;
  sustainablity?: string; // (sic – matches CSV column)
  non_profit_partner?: string;
  recalls_notices?: string;
  verification_status?: string;
  last_verified?: string; // normalised YYYY-MM-DD

  /* Numbers */
  year_founded?: number;

  /* Booleans */
  self_manufactured?: boolean;
  in_house_testing?: boolean;
  made_in_usa?: boolean;
  proprietary_blends?: boolean;
  woman_owned?: boolean;
  vegan?: boolean;
  allergen_free?: boolean;
  clinically_tested?: boolean;

  /* Arrays */
  manufacturing_locations?: string[];
  certification?: string[];
  product_categories?: string[];
  product_types?: string[];
  top_products?: string[];
  sources?: string[];
};
